<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 src/lib/assets/models/LPSilgii/Very Low Poly Silgii Head.gltf
-->

<script lang="ts">
  import { onMount } from 'svelte';

  import { Group } from 'three'
  import { T, forwardEventHandlers, useLoader } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'
  import { TextureLoader } from 'three'

  import * as THREE from 'three';
  // let mixer: THREE.AnimationMixer;

  // onMount(() => {
  const texture = useLoader(TextureLoader).load('src/lib/assets/models/LPSilgii/Silgii - Low Poly Head.png')

  export const ref = new Group()

  const gltf = useGltf('src/lib/assets/models/LPSilgii/Very Low Poly Silgii Head.gltf')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  // const animations = gltf.animations;

  const component = forwardEventHandlers()

  // mixer = new THREE.AnimationMixer(scene); 
  // animations.forEach((clip) => { 
  //   mixer.clipAction(clip).play(); 
  //   }); 
  //   const clock = new THREE.Clock(); 
  //   function animate() { 
  //     requestAnimationFrame(animate); 
  //     const delta = clock.getDelta(); 
  //     mixer.update(delta); renderer.render(scene, camera); 
  //     } 
      
  //     animate();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature">
        <T is={gltf.nodes.Root} />
        <T.Mesh name="SilgiiLP_Head" geometry={gltf.nodes.SilgiiLP_Head.geometry} material={gltf.materials.SilgiiMat} />
          <!-- Here, "texture" is acting like a regular promise -->
          {#await texture then value}
            <T.MeshStandardMaterial map={value} />
          {/await}
      </T.Group>
      <T.Group name="Spiral" position={[0, -13.37, 0.93]} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
